require.config({
	baseUrl:'./js',
	paths:{
		'jquery':'libs/jquery/jquery-1.11.3',
		'i18n':'libs/jquery/jquery.i18n.properties-1.0.9',
		'domReady':'libs/jquery/domReady',
		'mockjax':'libs/mock/jquery.mockjax',
		'framework':'framework/framework',
		'underscore':'libs/underscore/underscore-1.8.2',
		'user':'user',
		'role':'role',
		'locale':'locale',
		'signature':'signature'
	},
	waitSeconds:0,
	shim:{
		'i18n':['jquery'],
		'locale':['i18n'],
		'framework':{
			deps:['jquery','locale'],
			exports:'ef'
		},
		'api':{
			deps:['framework','api.config','mockjax'],
			exports:'api'
		},
	},
	map:{

	}
})(['login']);